In [3]:
import numpy as np

In [60]:
a = np.array([[-8,5],[6,6]])
print("matrix A :\n",a)
p = np.array([[5,-2],[-4,2]])
print("matrix p:\n",p)
pn = np.linalg.inv(p)
print("inverse of p:\n",pn)
c = np.matmul(a,p)
print("p(-1) x A x P is:\n",np.matmul(pn,c))


matrix A :
 [[-8  5]
 [ 6  6]]
matrix p:
 [[ 5 -2]
 [-4  2]]
inverse of p:
 [[1.  1. ]
 [2.  2.5]]
p(-1) x A x P is:
 [[ -54.   26.]
 [-105.   52.]]


In [42]:
a = np.array([[2,1,-1,2],[3,4,0,1],[1,5,2,6],[5,2,-1,-1]])
b = np.array([-6,1,-3,3])
np.linalg.solve(a,b)

array([ 1.00000000e+00, -4.24780983e-16,  4.00000000e+00, -2.00000000e+00])

In [29]:
a = np.array([[8,-32],[-2,8]])


(array([16.,  0.]),
 array([[ 0.9701425 ,  0.9701425 ],
        [-0.24253563,  0.24253563]]))

198